#!/bin/python
# -*- coding: utf-8 -*-

import requests

CITY = "4560349"
API_KEY = "7e9e6ea52fa8fc047201bf121caec312"
UNITS = "Imperial"
UNIT_KEY = "F"

REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?id={}&appid={}&units={}".format(CITY, API_KEY, UNITS))
if REQ.status_code == 200:
    CURRENT = REQ.json()["weather"][0]["description"].capitalize()
    TEMP = int(float(REQ.json()["main"]["temp"]))
print("{} °{}".format(TEMP, UNIT_KEY))
